quarkus:
  hibernate-orm:
    database:
      generation: update
  rest-client:
    world-time:
      url: http://worldtimeapi.org
      scope: jakarta.enterprise.context.ApplicationScoped
  swagger-ui:
    always-include: true

"%prod":
  quarkus:
    kubernetes-client:
      trust-certs: false
      api-server-url: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
      token: sha256~1RMrFrD0A8dpPZcfTDzLNBXtXnmC6CHtFEJR9NE4T3Q
    openshift:
      route:
        expose: true
      env:
        secrets: mysql
    kubernetes:
      deploy: true
    s2i:
      base-jvm-image: registry.access.redhat.com/ubi8/openjdk-17:1.16-1
    datasource:
      db-kind: mysql
      jdbc:
        url: jdbc:mysql://mysql.rjtmahinay-dev.svc.cluster.local:3306/demo
      password: ${database-password}
      username: ${database-user}


